name: AutoSub
options:
  bundleIdPrefix: com.autosub
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  AutoSub:
    type: application
    platform: macOS
    sources:
      - path: AutoSub
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.autosub.app
        INFOPLIST_FILE: AutoSub/Info.plist
        CODE_SIGN_ENTITLEMENTS: AutoSub/AutoSub.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        # Menu Bar App 設定
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: AutoSub/Info.plist
      properties:
        LSUIElement: true
        LSMinimumSystemVersion: "13.0"
        NSScreenCaptureUsageDescription: "Auto-Sub 需要存取螢幕錄製權限以擷取系統音訊"
    entitlements:
      path: AutoSub/AutoSub.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.automation.apple-events: true
